/**
 * Website Types
 *
 * Websites are workspace-scoped, agent-authored sites. One website is one
 * directory at one address — served at its own origin and opened as an ordinary
 * page (a tab in the browser window), backed by data that refresh scripts write
 * to disk.
 *
 * File structure:
 * {workspaceRootPath}/websites/{websiteSlug}/
 *   ├── index.html      - What the website's address opens. The file is the truth:
 *   │                     it may be written by file tools, and the host realigns
 *   │                     `contentDigest` from it (render leases are keyed to that
 *   │                     digest).
 *   ├── website.json       - WebsiteConfig (metadata, refresh spec, content digest).
 *   │                     Also the completion marker: refresh runs touch it last, and
 *   │                     the config watcher turns that into a `websites:changed` push.
 *   └── data/
 *       ├── store.sqlite  - Script-private working store (bun:sqlite; never read cross-process)
 *       └── snapshot.json - WebsiteDataSnapshot: the ONLY cross-process data contract,
 *                           written atomically by refresh scripts
 *
 * These types are environment-agnostic (renderer/main/webui safe). Storage,
 * validation, and execution live in @craft-agent/shared/websites.
 */

// ============================================================================
// Refresh
// ============================================================================

/** Runtime a website refresh script executes under (resolved via resolveScriptRuntime) */
export type WebsiteScriptRuntime = 'bun' | 'node' | 'python3';

/**
 * Scheduled refresh spec. Materialized as a synthetic cron automation matcher
 * with a single `script` action — never as an agent session.
 */
export interface WebsiteRefreshSpec {
  /** 5-field cron expression evaluated once per minute */
  cron: string;
  /** IANA timezone for cron evaluation (falls back to system local) */
  timezone?: string;
  /** Script path relative to the workspace root (must stay within it) */
  script: string;
  /** Extra argv appended after the script path */
  args?: string[];
  /** Script runtime (default: 'bun' — required for the bun:sqlite data store) */
  runtime?: WebsiteScriptRuntime;
  /** Per-run timeout in ms (default 60_000, clamped to [1_000, 900_000]) */
  timeoutMs?: number;
  /** Set to false to pause scheduling without deleting the spec */
  enabled?: boolean;
}

/** Outcome of the most recent refresh run (written by the executor, not the script) */
export interface WebsiteRefreshStatus {
  /** Completion timestamp (epoch ms) */
  at: number;
  ok: boolean;
  durationMs: number;
  /** Truncated stderr/error when ok is false */
  error?: string;
}

// ============================================================================
// Data snapshot (cross-process contract)
// ============================================================================

/** One timeseries datapoint */
export interface WebsiteSeriesPoint {
  /** Timestamp (epoch ms) */
  t: number;
  /** Numeric value */
  v: number;
}

/**
 * Contents of websites/{slug}/data/snapshot.json — the only website data read
 * outside the refresh script. Always written atomically (tmp + rename).
 */
export interface WebsiteDataSnapshot {
  version: 1;
  /** When the snapshot was exported (epoch ms) */
  generatedAt: number;
  /** Key-value entries (values are JSON-serializable) */
  kv: Record<string, unknown>;
  /** Named timeseries, each ordered by ascending t */
  series: Record<string, WebsiteSeriesPoint[]>;
}

// ============================================================================
// Preview thumbnail (cached poster)
// ============================================================================

/**
 * Pointer to a website's cached preview poster at websites/{slug}/thumbnail.jpg.
 *
 * Managed field (written only by `recordWebsiteThumbnail`, excluded from
 * `updateWebsite`). The poster is generated by Electron's offscreen capture and
 * served as a flat image on every host. It is STALE when `digest` no longer
 * equals the website's current `contentDigest` — the grid then falls back to the
 * placeholder (data-only refreshes deliberately do not invalidate it in v1).
 */
export interface WebsiteThumbnailInfo {
  /** contentDigest the poster was captured for (sha256 hex) */
  digest: string;
  /** Capture timestamp (epoch ms) */
  capturedAt: number;
  /** Stored image pixel dimensions */
  width: number;
  height: number;
}

// ============================================================================
// Website config
// ============================================================================

/**
 * Main website configuration (stored in website.json).
 *
 * website.json is deliberately the last file a refresh run touches: the config
 * watcher reacts to it (and only it) with a `websites:changed` push, so a
 * half-written data/ directory is never observed as "done".
 */
export interface WebsiteConfig {
  schemaVersion: 1;
  /** Stable id, e.g. website_1a2b3c4d */
  id: string;
  slug: string;
  name: string;
  /** Short description shown in lists */
  description?: string;
  /** Stable Project ID this website belongs to (never the project slug) */
  projectId?: string;
  /**
   * The conversation this website was created from — a weak reference, and the
   * website's only record of *why* it exists. A dangling id is normal (the
   * conversation may have been deleted); readers show the origin only while
   * that session still exists.
   */
  originSessionId?: string;
  createdAt: number;
  updatedAt: number;
  /** Scheduled data refresh (absent = manual/agent-driven data only) */
  refresh?: WebsiteRefreshSpec;
  /** Outcome of the most recent refresh run */
  lastRefresh?: WebsiteRefreshStatus;
  /** sha256 hex of index.html; absent until content is first saved */
  contentDigest?: string;
  /** Cached preview poster pointer (absent = none captured yet) */
  thumbnail?: WebsiteThumbnailInfo;
}
